# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/t30-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/acer/t30-common/proprietary/bin/glgps_nvidiaTegra2android:system/bin/glgps_nvidiaTegra2android \
    vendor/acer/t30-common/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/acer/t30-common/proprietary/bin/rild:system/bin/rild \
    vendor/acer/t30-common/proprietary/bin/tf_daemon:system/bin/tf_daemon \
    vendor/acer/t30-common/proprietary/etc/acer_ril.db:system/etc/acer_ril.db \
    vendor/acer/t30-common/proprietary/etc/enctune.conf:system/etc/enctune.conf \
    vendor/acer/t30-common/proprietary/etc/firmware/UartSet1024Kbps.bin:system/etc/firmware/UartSet1024Kbps.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/UartSet2048Kbps.bin:system/etc/firmware/UartSet2048Kbps.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/UartSet3Mbps.bin:system/etc/firmware/UartSet3Mbps.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
    vendor/acer/t30-common/proprietary/etc/firmware/es305.bin:system/etc/firmware/es305.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/nvavp_vid_ucode.bin:system/etc/firmware/nvavp_vid_ucode.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
    vendor/acer/t30-common/proprietary/etc/firmware/spkeq_48k.bin:system/etc/firmware/spkeq_48k.bin \
    vendor/acer/t30-common/proprietary/etc/model_frontal.xml:system/etc/model_frontal.xml \
    vendor/acer/t30-common/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/acer/t30-common/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/acer/t30-common/proprietary/lib/egl/libEGL_tegra_impl.so:system/lib/egl/libEGL_tegra_impl.so \
    vendor/acer/t30-common/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/acer/t30-common/proprietary/lib/egl/libGLESv1_CM_tegra_impl.so:system/lib/egl/libGLESv1_CM_tegra_impl.so \
    vendor/acer/t30-common/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/acer/t30-common/proprietary/lib/egl/libGLESv2_tegra_impl.so:system/lib/egl/libGLESv2_tegra_impl.so \
    vendor/acer/t30-common/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/acer/t30-common/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/acer/t30-common/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/acer/t30-common/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/acer/t30-common/proprietary/lib/hw/lights.tegra.so:system/lib/hw/lights.tegra.so \
    vendor/acer/t30-common/proprietary/lib/hw/sensors.tegra.so:system/lib/hw/sensors.tegra.so \
    vendor/acer/t30-common/proprietary/lib/liba1026.so:system/lib/liba1026.so \
    vendor/acer/t30-common/proprietary/lib/libakmd.so:system/lib/libakmd.so \
    vendor/acer/t30-common/proprietary/lib/libami.so:system/lib/libami.so \
    vendor/acer/t30-common/proprietary/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
    vendor/acer/t30-common/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/acer/t30-common/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/acer/t30-common/proprietary/lib/libhuawei-ril.so:system/lib/libhuawei-ril.so \
    vendor/acer/t30-common/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/acer/t30-common/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/acer/t30-common/proprietary/lib/libmpl.so:system/lib/libmpl.so \
    vendor/acer/t30-common/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/acer/t30-common/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/acer/t30-common/proprietary/lib/libnvaudioservice.so:system/lib/libnvaudioservice.so \
    vendor/acer/t30-common/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/acer/t30-common/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/acer/t30-common/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
    vendor/acer/t30-common/proprietary/lib/libnvcap.so:system/lib/libnvcap.so \
    vendor/acer/t30-common/proprietary/lib/libnvcap_video.so:system/lib/libnvcap_video.so \
    vendor/acer/t30-common/proprietary/lib/libnvcapclk.so:system/lib/libnvcapclk.so \
    vendor/acer/t30-common/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
    vendor/acer/t30-common/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/acer/t30-common/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/acer/t30-common/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/acer/t30-common/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/acer/t30-common/proprietary/lib/libnvglsi.so:system/lib/libnvglsi.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/acer/t30-common/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/acer/t30-common/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/acer/t30-common/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/acer/t30-common/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/acer/t30-common/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/acer/t30-common/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/acer/t30-common/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/acer/t30-common/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/acer/t30-common/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/acer/t30-common/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/acer/t30-common/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/acer/t30-common/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/acer/t30-common/proprietary/lib/libnvremoteevtmgr.so:system/lib/libnvremoteevtmgr.so \
    vendor/acer/t30-common/proprietary/lib/libnvremotell.so:system/lib/libnvremotell.so \
    vendor/acer/t30-common/proprietary/lib/libnvremoteprotocol.so:system/lib/libnvremoteprotocol.so \
    vendor/acer/t30-common/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/acer/t30-common/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/acer/t30-common/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/acer/t30-common/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
    vendor/acer/t30-common/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/acer/t30-common/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/acer/t30-common/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/acer/t30-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/acer/t30-common/proprietary/lib/libtf_crypto_sst.so:system/lib/libtf_crypto_sst.so \
    vendor/acer/t30-common/proprietary/lib/libtjpg.so:system/lib/libtjpg.so
